name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          default: true

      - name: Quick check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      # Run tests again in Release mode to attempt to catch UB
      - name: Run tests (Release)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
